### ISSUE TITLE
두 개의 ArrayList를 equals로 비교가능한가요?

### ISSUE THREAD

**Issue by kwanghoon** [kwanghoon/SmallBasicDataCollection#2]
@H-sooyeon 

https://github.com/kwanghoon/SmallBasicDataCollection/blob/ebc2651078c32208d2894ef41fbd95fb003ab96b/src/com/syntax/SyntaxCompletionDataManager.java#L119

두 개의 ArrayList가 동일한지 비교하는 의도로 작성한 것 같은데...

다음의 관점에서 확인 부탁해요. 
 - 동일한 원소들이 순서가 달라도 .equals에서 정렬해서 동일함을 판단하는지
 - 각 원소 비교할 때 "abcd" == "abcd"  (내용 비교인지) 아니면 String x = "abcd";   x == x  (주소 비교인지) 확인해주세요.

**Comment by H-sooyeon** [comment]
119번 코드의 의미는
존재하는지  확인하고자 하는 한 개의 구문 후보인 arr과, 만든 해쉬맵 구문후보를 비교하는 거에요!
arr과 함께 전달받은 상태값으로 해쉬맵에서 해당 상태에 해당하는 구문 후보들만을 뽑은 후,
이를 하나씩 arr과 비교해요.
* arr-> [T, CR, NT, MoreThanOneStmt] 처럼 저장되어서 전달돼요!

equals()는 정렬은 하지 않고 비교만 하며, 순서를 바꿔서 제공하는 경우 같지 않다고 리턴돼요.
그리고 주소가 아닌 두 대상의 값 자체를 비교해요!

**Comment by kwanghoon** [comment]
@H-sooyeon 
스몰베이직 프로그램에서 얻은 구문 후보 데이터를 사용해보면 부족한 후보들이 있지 않나 하는 생각이 들거든.
예를 들어 x = x 다음에 tab을 치면 +, -, *, / 연산자로 시작하는 후보들이 나와야하는데, 이 후보들이 모두 나오지 않아...

그 원인이 무엇일까 고민 중이고, 혹시 이 코드에 버그가 있지 않았을까 생각해보았는데 이 코드에 버그가 있어서 후보가 빠지거나 하지는 않은 것 같다. OK

구문 후보 데이터가 예제에 나타난 것들을 모두 다 모았는지 함께 고민해봅시다~

**Comment by H-sooyeon** [comment]
날짜: 2023.03.11 오후 03:59:30 (GMT+09:00)
제목: Re: [kwanghoon/SmallBasicDataCollection] 두 개의 ArrayList를 equals로 비교가능한가요? (Issue #2)

@H-sooyeon
스몰베이직 프로그램에서 얻은 구문 후보 데이터를 사용해보면 부족한 후보들이 있지 않나 하는 생각이 들거든.
예를 들어 x = x 을 치면 +, -, *, / 연산자로 시작하는 후보들이 모두 나오는것이 아니다.
그 원인이 무엇일까 고민 중이고, 혹시 이 코드에 버그가 있지 않았을까 생각해보았는데 이 코드에 버그가 있어서 후보가 빠지거나 하지는 않은 것 같다. OK
구문 후보 데이터가 예제에 나타난 것들을 모두 다 모았는지 함께 고민해봅시다~

**Comment by kwanghoon** [comment]
@H-sooyeon 

data 폴더에 두 가지 파일을 업로드함
 - smallbasic-states.txt  [각 파싱 상태가 문법에서 의미하는 바, Items]
 - smallbasic-syntax-completion-candidates-results.txt  [Collect한 프로그램에서 얻은 구문 후보 목록 결과]
 
Collect한 스몰베이직 프로그램 구문 후보 목록을 이용할 때 구문 후보의 수가 기대한것 대비 적게 나온 이유에 대해 조사하고 있는데
일단 구문 후보 목록에는 오류라 볼만한 것은 없어 보이고, 
탭을 눌렀을때 서버가 1개의 상태만 MySmallBasic에 전달했는데, 때로는 여러 개의 상태들을 리턴해야하는데 그렇지 않은 것이 원인으로 보입니다. 조사하고 있습니다~

**Comment by H-sooyeon** [comment]
날짜: 2023.03.12 오후 04:38:58 (GMT+09:00)
제목: Re: [kwanghoon/SmallBasicDataCollection] 두 개의 ArrayList를 equals로 비교가능한가요? (Issue #2)

@H-sooyeon
data 폴더에 두 가지 파일을 업로드함

smallbasic-states.txt [각 파싱 상태가 문법에서 의미하는 바, Items]
smallbasic-syntax-completion-candidates-results.txt [Collect한 프로그램에서 얻은 구문 후보 목록 결과]

Collect한 스몰베이직 프로그램 구문 후보 목록을 이용할 때 구문 후보의 수가 기대한것 대비 적게 나온 이유에 대해 조사하고 있는데
일단 구문 후보 목록에는 오류라 볼만한 것은 없어 보이고,
탭을 눌렀을때 서버가 1개의 상태만 MySmallBasic에 전달했는데, 때로는 여러 개의 상태들을 리턴해야하는데 그렇지 않은 것이 원인으로 보입니다. 조사하고 있습니다~
